### PR TITLE
ICU-22724 Update ICU4C API reference docs for 76.1

### PR DESCRIPTION
**Pull request by mihnita**
https://unicode-org.atlassian.net/browse/ICU-22724 ICU 76 BRS task

### CODE REVIEW

**Comment by markusicu** [comment]
in the future please make separate commits for
- C docs
- Java docs
- readme

in order to bog down the GitHub review window less...

**Comment by markusicu** [comment]
I am having a hard time looking at this without just rubber-stamping.
Why is there a .jar file? (I see that in the file types list.)

**Comment by mihnita** [comment]
Sorry, will do next time.
If you want I can redo it with 3 separate commits.

There is no jar.
There was a jar before, which was a mistake.
It is now deleted.

**Review by markusicu — APPROVED** [review]
I see now that you are *deleting* icu4j-75_1-fulljavadoc.jar -- thanks!

**Pull request merged**
