### PR TITLE
Update icu4c and icu4j apidocs to release-68-1 tag

### PR DESCRIPTION
**Pull request by hugovdm**
* icu4c docs created by "make doc-searchengine".
* icu4j docs extracted from the jar on the ICU 68.1 GitHub Release page: https://github.com/unicode-org/icu/releases/download/release-68-1/icu4j-68_1-docs.jar
* pull request branch should soon be served at: https://hugovdm.github.io/icu-docs/
  * (building takes more time than I expected. "Your GitHub Pages site is currently being built from the apidoc_release_68_1 branch")

### CODE REVIEW

**Comment by hugovdm** [comment]
"Your site is having problems building: The variable {{host} on line 61 in docs/userguide/formatparse/messages/index.md was not properly closed with }}."

Fixing.

**Review by sven-oly — APPROVED** [review]

**Review by yumaoka — APPROVED** [review]
LGTM

**Comment by hugovdm** [comment]
Force-push updated commit messages with ticket number prefixes (as is standard in the icu repository).

Partially did it to see if that triggers a faster serving on https://hugovdm.github.io/icu-docs/

**Comment by hugovdm** [comment]
So yes, indeed it does make things fast: *first* set up GitHub Pages settings, *then* push to the branch.

**Pull request merged**
