### PR TITLE
ICU 21480 ICU4C docs for rev 69rc

### PR DESCRIPTION
**Pull request by sven-oly**
Ready for review of ICU4C documentation update.
Following instructions here: http://site.icu-project.org/processes/release/tasks/docs#TOC-Build-API-documentations
and
https://unicode-org.github.io/icu-docs/HOWTO-Update.html

### CODE REVIEW

**Review by hugovdm — APPROVED** [review]
Took a cursory look - looks reasonable to me, and I feel further review can be done after merge by comparing /released/ and /dev/. Thanks!

**Comment by sven-oly** [comment]
I wonder about the HTML files with dir_ and a bunch of numbers.hmtl, e.g.,
dir_0119ce638985e8a1561a00fdb5f76ff6.html

Are these legitimate API doc files?

**Comment by hugovdm** [comment]
Looking at these files, they seem to be a directory index:

* https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/dir_4f66ea94ab501ae66e9edea2ec5eed02.html
* https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/dir_0119ce638985e8a1561a00fdb5f76ff6.html
* https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/dir_f59c6450ff718ff1b085cfd1c36acbd7.html
* https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/dir_85f13b36d96bf7d19941498801eef432.html

It's the top nav of source files that link there, e.g. clicking "layout" at the top (right of "layoutex") on these pages:

* https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/plruns_8h.html
* https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/plruns_8h_source.html
* https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/RunArrays_8h.html
* (etc)

I've done no deeper investigation than look at these (and other of the dir_ files for directories that I believe look empty because they export no public API).

**Comment by srl295** [comment]
> Looking at these files, they seem to be a directory index:
> 
> * https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/dir_4f66ea94ab501ae66e9edea2ec5eed02.html

yes, generated by doxygen

**Review by srl295 — APPROVED** [review]
RSLGTM

**Pull request merged**
