### PR TITLE
Update Dev API docs at icu tag release-68-rc

### PR DESCRIPTION
**Pull request by hugovdm**
See the output at: https://hugovdm.github.io/icu-docs/apidoc/dev/icu4c/ & https://hugovdm.github.io/icu-docs/apidoc/dev/icu4j/

I'm not using a branch named "master". We could change the instructions if there's risk of accidentally pushing to unicode-org/icu-docs, but I'm guessing there's appropriate branch protection rules on the master branch?

* With an ICU repository at **release-68-rc**:
  * Ran `./runConfigureICU --enable-debug --disable-release Linux --disable-layoutex && make doc-searchengine` for ICU4C,
  * Ran `JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 ant docs` for ICU4J.
* Replaced the contents of apidoc/dev/icu4c/ in this repository with the resulting icu4c/source/doc/html/.
* Replaced the contents of apidoc/dev/icu4j/ in this repository with the resulting icu4j/doc/.

### CODE REVIEW

**Comment by srl295** [comment]
Icu4j- I think you need java 7. @yumaoka ?

**Comment by hugovdm** [comment]
Ah nice, Java 8 succeeded:

$ JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 ant docs

I still need to grab Java 7 (to make Eclipse happy too). It's not just an "apt-get" away. :-)

**Comment by hugovdm** [comment]
Trial run, comparing doc output for release-67-1 and icu-docs/apidoc/released/ I find a bunch of differences.
I hope they're simply due to: `Doxygen 1.8.17` instead of `Doxygen 1.8.13`, and surprisingly, `javadoc (1.8.0_232)` instead of `javadoc (1.8.0_242)` (so my java-8-openjdk-amd64 has an older javadoc than was used to generate the published docs).

**Review by markusicu — DISMISSED** [review]
Please wait until we have an ICU 68 release candidate tag and maintenance branch -- should be today.

After that, please coordinate with the owners of the corresponding BRS tasks, rows 67 & 69 (@sven-oly & @yumaoka ), just so that not two people are doing the same work. But I am sure they wouldn't mind someone else jumping in :-)

**Comment by hugovdm** [comment]
Thanks Markus! I'll look at BRS tasks and get a sense of how this flow typically works.

(For myself, this was just inspired by wanting to mark https://unicode-org.atlassian.net/browse/ICU-21304 as "done". :-)

**Comment by markusicu** [comment]
Thanks!

Spot-checking... I happened to look for the new UErrorCode constant U_INPUT_TOO_LONG_ERROR, in utypes.h. It does not show up in the API docs. @srl295 ideas? @hugovdm were there any warnings on the command line?

https://github.com/unicode-org/icu/blob/master/icu4c/source/common/unicode/utypes.h
https://hugovdm.github.io/icu-docs/apidoc/dev/icu4c/utypes_8h.html#a3343c1c8a8377277046774691c98d78c

Other draft ICU 68 APIs seem to be there, such as `icu::LocaleMatcher::Builder::setNoDefaultLocale()`.

https://hugovdm.github.io/icu-docs/apidoc/dev/icu4c/classicu_1_1LocaleMatcher_1_1Builder.html

**Comment by markusicu** [comment]
On the ICU4J landing page I see "Copyright © 2016 Unicode, Inc. and others." @yumaoka where does this string get updated? We should use the same text as in the source files.

**Comment by yumaoka** [comment]
>On the ICU4J landing page I see "Copyright © 2016 Unicode, Inc. and others." @yumaoka where does this string get updated? We should use the same text as in the source files.

I'll investigate this after RC.

**Comment by yumaoka** [comment]
>Icu4j- I think you need java 7. @yumaoka ?

Official build just use Java 7 as bootstrap. For now Java docs are handled by JDK 8.

**Comment by hugovdm** [comment]
Redone from my history:

```
 9997  [2020-10-10 02:02:21 +0200] cd ~/git/icu/icu4c/source/
 9998  [2020-10-10 02:02:32 +0200] git checkout release-68-rc 
 9999  [2020-10-10 02:02:37 +0200] make clean
10000  [2020-10-10 02:02:50 +0200] ./runConfigureICU --enable-debug --disable-release Linux --disable-layoutex
10001  [2020-10-10 02:03:03 +0200] make doc
10002  [2020-10-10 02:05:43 +0200] diff doc/html/ ~/git/icu-docs/apidoc/dev/icu4c/

-> no diffs

$ rgrep U_INPUT_TOO_LONG_ERROR doc/html/
doc/html/utypes_8h_source.html:<div class="line"><a name="l00490"></a><span class="lineno">  490</span>&#160;    U_INPUT_TOO_LONG_ERROR = 31,</div>
```

So it's only mentioned once, in the utypes_8h_source.html file. Code:

```
#ifndef U_HIDE_DRAFT_API
    /**
     * The input is impractically long for an operation.
     * It is rejected because it may lead to problems such as excessive
     * processing time, stack depth, or heap memory requirements.
     *
     * @draft ICU 68
     */
    U_INPUT_TOO_LONG_ERROR = 31,
#endif  // U_HIDE_DRAFT_API
```

Did I maybe not generate anything for such draft APIs? :thinking:

**Review by yumaoka — CHANGES_REQUESTED** [review]
**_ICU4J API docs in this PR was not created with JCite._**

If you're publishing J API docs, please follow the instruction.

http://site.icu-project.org/processes/release/tasks/docs#TOC-Upload-API-documentations

ICU4J
Build the API documentation pages for the new release. "ant docs"

Note: JCite must be installed: http://site.icu-project.org/setup/java/ant#TOC-Building-ICU4J-API-Reference-Document-with-JCite

For official release build, http://site.icu-project.org/processes/release/tasks/release-build explains the necessary set up - including JDK, JCite, bootstrap jar, etc..

I've already built ICU4J release files for 68RC, and uploaded to the release page: http://site.icu-project.org/processes/release/tasks/release-build - Please use icu4j-68rc-docs.jar attached in the page.

**Comment by hugovdm** [comment]
Looking at https://hugovdm.github.io/icu-docs/apidoc/dev/icu4c/utypes_8h_source.html , line 490 doesn't have a link, while line 498 does, suggesting my commands were hiding draft APIs but not deprecated APIs.

**Comment by hugovdm** [comment]
Line 84 of:
- https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/utypes_8h_source.html
- https://hugovdm.github.io/icu-docs/apidoc/dev/icu4c/utypes_8h_source.html

Looks like both the old run and this new run have `#define U_HIDE_DRAFT_API 1`, can also be seen at:

- https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/utypes_8h.html#a06945159db789670a11e785b4f691b41
- https://hugovdm.github.io/icu-docs/apidoc/dev/icu4c/utypes_8h.html#a06945159db789670a11e785b4f691b41

It seems we exclude draft APIs?

**Comment by markusicu** [comment]
> Looking at https://hugovdm.github.io/icu-docs/apidoc/dev/icu4c/utypes_8h_source.html , line 490 doesn't have a link, while line 498 does, suggesting my commands were hiding draft APIs but not deprecated APIs.

But other new and old drafts do show up.
I looked at the API change report, and this constant is missing from that, too. Maybe doxygen doesn't like how I wrote that?
Could you please submit a ticket for this issue?

**Comment by hugovdm** [comment]
Yeah: I found line 2162 of https://hugovdm.github.io/icu-docs/apidoc/dev/icu4c/numberformatter_8h_source.html, usage(), does show up:
https://hugovdm.github.io/icu-docs/apidoc/dev/icu4c/classicu_1_1number_1_1NumberFormatterSettings.html#a93708dbf5affad9233623f46a910a048

I thus also think doxygen might be doing something unexpected with the preprocessor/defines handling - such that when processing utypes.h, it allows U_HIDE_DRAFT to get defined, while it doesn't get defined when processing numberformatter.h ...

**Comment by hugovdm** [comment]
> I looked at the API change report, and this constant is missing from that, too. Maybe doxygen doesn't like how I wrote that?
> Could you please submit a ticket for this issue?

I filed https://unicode-org.atlassian.net/browse/ICU-21329 - components "others" (didn't find a docs-related component). Please adjust the ticket as necessary?

/me afk (sleep)

**Comment by yumaoka** [comment]
>On the ICU4J landing page I see "Copyright © 2016 Unicode, Inc. and others." @yumaoka where does this string get updated? We should use the same text as in the source files.

It's defined in build.xml as property. We can override property value with build.properties, or build-local.properties.

It looks we also have the same copyright text. I guess we can consolidate them and put them into a single properties file later.

**Comment by hugovdm** [comment]
> **_ICU4J API docs in this PR was not created with JCite._**
> 
> If you're publishing J API docs, please follow the instruction.
> 
> http://site.icu-project.org/processes/release/tasks/docs#TOC-Upload-API-documentations

Thanks for the pointer! As I wasn't following procedure for this (didn't intend to steal a BRS task), I started at https://unicode-org.github.io/icu-docs/HOWTO-Update.html - I'm not yet decided whether I think it makes sense to link from there to http://site.icu-project.org/processes/release/tasks/docs, perhaps not necessary. "Just follow the correct processes" should do the trick.

> I've already built ICU4J release files for 68RC, and uploaded to the release page: http://site.icu-project.org/processes/release/tasks/release-build - Please use icu4j-68rc-docs.jar attached in the page.

Thanks!

I think we can then close this PR? Closing - https://unicode-org.atlassian.net/browse/ICU-21329 was a useful outcome, and it refers to this conversation. I'll leave my hugovdm.github.io/icu-docs pointing at this branch for the links and references to be stable.

**Comment by hugovdm** [comment]
Not closing yet, but going to bed:

- I would be happy to resume this later (Monday?), or
- Someone not in a European timezone can take it over.

**Comment by yumaoka** [comment]
> I think it makes sense to link from there to http://site.icu-project.org/processes/release/tasks/docs

We maintain all instructions in ICU project site. BRS sheet has link to instruction.  These are master BRS reference.
In the BRS spreadsheet - the task description link should send you to http://site.icu-project.org/processes/release/tasks/docs .
And the section - Upload API documentations includes the link to  https://unicode-org.github.io/icu-docs/HOWTO-Update.html

The HOWTO-Update.html was written by Steven - it looks he just wanted to put the detailed description about uploading docs in the git repo. Of course, including link back to ICU BRS instruction is not harmful.. but it's just optional. What we need is to make sure every instruction description can be found from the BRS spreadsheet.

**Comment by rajasibero** [comment]
> See the output at: https://hugovdm.github.io/icu-docs/apidoc/dev/icu4c/ & https://hugovdm.github.io/icu-docs/apidoc/dev/icu4j/
> 
> I'm not using a branch named "master". We could change the instructions if there's risk of accidentally pushing to unicode-org/icu-docs, but I'm guessing there's appropriate branch protection rules on the master branch?
> 
> * With an ICU repository at **release-68-rc**:
>   
>   * Ran `./runConfigureICU --enable-debug --disable-release Linux --disable-layoutex && make doc` for ICU4C,
>   * Ran `JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 ant docs` for ICU4J.
> * Replaced the contents of apidoc/dev/icu4c/ in this repository with the resulting icu4c/source/doc/html/.
> * Replaced the contents of apidoc/dev/icu4j/ in this repository with the resulting icu4j/doc/.

**Comment by yumaoka** [comment]
>@hugovdm Regenerate ICU4J docs with JCite 1.13.0 available.

No it looks good to me. To check if JCite is working or not,  check [com.ibm.icu.text.DateTimePatternGenerator#getBestPattern](https://hugovdm.github.io/icu-docs/apidoc/dev/icu4j/com/ibm/icu/text/DateTimePatternGenerator.html#getBestPattern-java.lang.String-). If code block is quoted properly, then JCite is working. If code block does not show up, it's not enabled.
The latest update looks good.

In ICU4J ant build.xml, we have targets "release*". These are designed for release tasks, and do the strict checking for build environment. I'd update BRS doc to use "release*" target for J API doc generation, instead of just running "doc" target.

I know most of ICU4J developers are not setting up proper environment. To do that, you need older version of Java runtime, along with newer JDK. This set up is not trivial on some environment, such as Mac OS - I don't know where to get Java 7 runtime for Mac at this point. For this reason, ICU4J build script does not refuse to build ICU4J without all dependencies on release, and ICU4J developer can skip some extra set up. We could add more visible warning when build is done on env without full configuration for release.

**Review by yumaoka — APPROVED** [review]
Latest change for ICU4J API docs look good to me.

**Comment by hugovdm** [comment]
Dinner break. I can't update the Sites pages, did you mean you'll update the pages? I'll take a closer look at release targets etc, and could propose Sites changes via a Google Doc.

**Comment by hugovdm** [comment]
It looks like "ant releaseDocs" only adds .jar file creation (for a bundle of docs). In any case, the jar contents matches what's currently in this branch (except for the timestamps being updated again).

For ICU4C, I ran "make doc" instead of "make doc-searchengine", as per instructions in http://site.icu-project.org/processes/release/tasks/docs#TOC-Build-API-documentations. So need to update this too.

**Comment by markusicu** [comment]
This (publishing the API docs) plus one other task is holding up announcing the release candidate and letting others test ICU 68. Please move this along.

**Comment by hugovdm** [comment]
If going via the .jar file for ICU4J, there's also a apidoc/dev/icu4j/META-INF/MANIFEST.MF file. Just following the instructions I found gives no MANIFEST.MF - this PR now doesn't have that file. (This file may not matter.)

And running "make doc-searchengine" provides a "search" directory which apparently wasn't in the previous output.

Can someone confirm that 7da5bb255fc03d3f0bc33a79023c12448a8af015 is good - adding search?

**Comment by hugovdm** [comment]
I squashed. **There is a difference to what @yumaoka approved, the addition of commit 7da5bb2** - please confirm this addition is correct before approving.

**Comment by hugovdm** [comment]
Additionally:
- one more force-push just to change the commit message, adding ICU ticket number ICU-21250: "ICU 68.1 Release BRS",
- icu-docs is not configured to dismiss reviews upon further commits - which means I could merge, not blocked on the additional changes, but I would prefer explicit confirmation.

**Comment by markusicu** [comment]
The instructions say `make doc-searchengine` and I think we used to have the search box, so that should be good. I assume it's an oversight that the 67 docs don't have it.

**Comment by markusicu** [comment]
I am curious why you changed from the rc ticket to the final ticket. If we don't have to change the docs again after rc it shouldn't matter, but the rc ticket made sense too. ?

**Comment by hugovdm** [comment]
I had no ticket number previously. Now I found the RC ticket number - force-pushed again, please pardon the chaos.

**Comment by hugovdm** [comment]
I'm going ahead and merging, with ticket number ICU-21249.

**Comment by markusicu** [comment]
Thanks!

**Pull request merged**
