### PR TITLE
rounded logo

### PR DESCRIPTION
**Pull request by srl295**
- this is the logo as "currently" on the ICU site, as opposed to the squarish one.
- include Intaglio source file https://www.purgatorydesign.com (this was previously in a .zip file)

### CODE REVIEW

**Comment by srl295** [comment]
> Wait, I like the straight logo better. When did we change to this weird rounded one?

then… don't approve this?

https://github.com/unicode-org/icu has the rounded one … where do you see the straight one now?

**Comment by srl295** [comment]
maybe this isnt' the 'current' logo, only the one in my head and on preesentations.

**Comment by sffc** [comment]
I'm pretty sure icu-project.org had the square logo, before Mark removed it and replaced it with the new Unicode logo.

**Comment by srl295** [comment]
> I'm pretty sure icu-project.org had the square logo, before Mark removed it and replaced it with the new Unicode logo.

yes, that's what the wayback link above proves ^

**Comment by srl295** [comment]
If we accept This PR: rounded

If we reject this PR ('current'):  square

**Comment by srl295** [comment]
@sffc closing this because I think you are right, I was inadvertently trying to regress the logo

**Comment by srl295** [comment]
I'll keep the branch around.

**Comment by srl295** [comment]
https://github.com/unicode-org/icu-docs#icu-docs---international-components-for-unicode-docs still has the rounded logo, needs to be fixed

**Pull request closed without merging**
